name: Discord Notification

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content":"🚀 New push to repository by ${{ github.actor }}"}' \
          "https://discord.com/api/webhooks/1482804224122163270/t1Wj_U9gr1rBvpTwBmT9O1lvRyujTDhzSS9sS7WF_zl6TrhYegm9UU0CT0bsVYbpZ0-T"
